name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.version_tag.outputs.value }}
      build_date: ${{ steps.build_date.outputs.value }}
    steps:
      - name: Format version tag
        shell: bash
        id: version_tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "value=$TAG" >> $GITHUB_OUTPUT
      - name: Build date
        shell: bash
        id: build_date
        run: echo "value=$(date +%FT%T%z)" >> $GITHUB_OUTPUT

  release:
    needs:
      - prepare
    runs-on: ubuntu-latest
    env:
      VERSION_TAG: ${{ needs.prepare.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
